name: Deploy Frontend (Angular) to SWA

on:
  push:
    branches:
      - master # Branche principale

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy Angular
    
    # L'environnement et l'URL sont gérés par SWA
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.web_app_url }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build Angular
        run: |
          npm install
          chmod +x ./node_modules/.bin/ng
          # Sortie Angular dans un dossier 'output' à la racine du workspace
          ./node_modules/.bin/ng build --output-path ./output
        working-directory: Hexagonal # <<< Le dossier de votre application Angular

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: azure/static-web-apps-deploy@v1 
        with:
          # Utilisation du jeton de déploiement SWA
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_OCEAN_00C11CE03 }}
          
          # PARAMÈTRES SWA
          app_location: '/Hexagonal' # Le dossier où se trouve le package.json (source)
          output_location: 'output/browser' # La sortie après la construction Angular (fichiers .html, .js)
          api_location: '' # Laisser vide, car l'API est déployée séparément
          
          # On indique que l'application a été construite manuellement
          skip_app_build: true 
          skip_api_build: true # L'API est déjà gérée
