name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  # NOUVEAU JOB 1 : CONSTRUCTION ET UPLOAD D'ARTEFACT
  build:
    runs-on: ubuntu-latest
    name: Build Angular App
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build Angular
        run: |
          npm install
          chmod +x ./node_modules/.bin/ng
          # Build vers le dossier de l'artefact
          ./node_modules/.bin/ng build --output-path dist/final_output
        working-directory: Hexagonal 

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: angular-frontend
          # L'artefact est le contenu du dossier de sortie (Hexagonal/dist/final_output)
          path: Hexagonal/dist/final_output

  # NOUVEAU JOB 2 : TÉLÉCHARGEMENT ET DÉPLOIEMENT
  deploy:
    runs-on: ubuntu-latest
    needs: build # Dépend du succès du job de build
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Deploy to Azure SWA
    
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: angular-frontend
          # Le téléchargement place l'artefact (index.html, etc.) directement à la racine du workspace.
          path: .

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_OCEAN_00C11CE03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          
          # Paramètres de déploiement simplifiés :
          app_location: "" # Vide
          api_location: ""
          # Le chemin d'artefact est maintenant la racine du workspace.
          output_location: "." 
          skip_app_build: true
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_OCEAN_00C11CE03 }}
          action: "close"
